apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: okhuco4sy-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: okhuco4sy-go 
  name: okhuco4sy-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: okhuco4sy-go 
